//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrabble2018.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Skin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scrabble2018.Properties.Skin", typeof(Skin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2xLetter.
        /// </summary>
        public static string _2xLetter {
            get {
                return ResourceManager.GetString("2xLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2xWord.
        /// </summary>
        public static string _2xWord {
            get {
                return ResourceManager.GetString("2xWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3xLetter.
        /// </summary>
        public static string _3xLetter {
            get {
                return ResourceManager.GetString("3xLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3xWord.
        /// </summary>
        public static string _3xWord {
            get {
                return ResourceManager.GetString("3xWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: poyea@GitHub; Repository: poyea/scrabble.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Tile Form.
        /// </summary>
        public static string BlankTileForm {
            get {
                return ResourceManager.GetString("BlankTileForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Tile Types.
        /// </summary>
        public static string BoardTileTypes {
            get {
                return ResourceManager.GetString("BoardTileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a letter to represent the blank tile:.
        /// </summary>
        public static string ChooseLetter {
            get {
                return ResourceManager.GetString("ChooseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string DesktopInterface {
            get {
                return ResourceManager.GetString("DesktopInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH.
        /// </summary>
        public static string FinishButton {
            get {
                return ResourceManager.GetString("FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has finished swapping their tiles!.
        /// </summary>
        public static string FinishSwap {
            get {
                return ResourceManager.GetString("FinishSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH TURN.
        /// </summary>
        public static string FinishTurn {
            get {
                return ResourceManager.GetString("FinishTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} is first!.
        /// </summary>
        public static string FirstPlayer {
            get {
                return ResourceManager.GetString("FirstPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Judge: You didn&apos;t score. Please try again!.
        /// </summary>
        public static string GameJudge {
            get {
                return ResourceManager.GetString("GameJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a score of {0}, Player {1} is the winner!.
        /// </summary>
        public static string GameWinner {
            get {
                return ResourceManager.GetString("GameWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This internationalized and localized version of Scrabble was created by Nicole Anjuli Henry, Tulsiben Patel, Linh Nguyen, and Aurora Wang for our software i18n class at Middlebury Institute of International Studies at Monterey..
        /// </summary>
        public static string I18Nwiz {
            get {
                return ResourceManager.GetString("I18Nwiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string MobileButton1 {
            get {
                return ResourceManager.GetString("MobileButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAP.
        /// </summary>
        public static string MobileButton2 {
            get {
                return ResourceManager.GetString("MobileButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELOAD.
        /// </summary>
        public static string MobileButton3 {
            get {
                return ResourceManager.GetString("MobileButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH.
        /// </summary>
        public static string MobileFinishButton {
            get {
                return ResourceManager.GetString("MobileFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string MobileInterface {
            get {
                return ResourceManager.GetString("MobileInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your tiles!.
        /// </summary>
        public static string MobileLabel {
            get {
                return ResourceManager.GetString("MobileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrabble.
        /// </summary>
        public static string MobileName {
            get {
                return ResourceManager.GetString("MobileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now: P. {0} | Score: .
        /// </summary>
        public static string MobilePlayerandScore {
            get {
                return ResourceManager.GetString("MobilePlayerandScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Player: {0}.
        /// </summary>
        public static string MobilePlayerNow {
            get {
                return ResourceManager.GetString("MobilePlayerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAP.
        /// </summary>
        public static string MobileSwapButton {
            get {
                return ResourceManager.GetString("MobileSwapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} - Mobile Scrabble.
        /// </summary>
        public static string MobileTitle {
            get {
                return ResourceManager.GetString("MobileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner: P {0}, Score: {1}!.
        /// </summary>
        public static string MobileWinner {
            get {
                return ResourceManager.GetString("MobileWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your turn!.
        /// </summary>
        public static string MobileYourTurn {
            get {
                return ResourceManager.GetString("MobileYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need more friends to start Scrabble!!! Find friends!.
        /// </summary>
        public static string NeedFriends {
            get {
                return ResourceManager.GetString("NeedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t swap tiles now because less than 7 tiles are left in the bag!.
        /// </summary>
        public static string NoSwap {
            get {
                return ResourceManager.GetString("NoSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0} player game..
        /// </summary>
        public static string NumofPlayer {
            get {
                return ResourceManager.GetString("NumofPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0} player game....
        /// </summary>
        public static string NumofPlayers {
            get {
                return ResourceManager.GetString("NumofPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has passed!.
        /// </summary>
        public static string OtherPlayerPass {
            get {
                return ResourceManager.GetString("OtherPlayerPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has swapped their tiles!.
        /// </summary>
        public static string OtherPlayerSwap {
            get {
                return ResourceManager.GetString("OtherPlayerSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}&apos;s score is: {1}.
        /// </summary>
        public static string PlayerCSScores {
            get {
                return ResourceManager.GetString("PlayerCSScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 4.
        /// </summary>
        public static string PlayerFour {
            get {
                return ResourceManager.GetString("PlayerFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1.
        /// </summary>
        public static string PlayerOne {
            get {
                return ResourceManager.GetString("PlayerOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has decided to pass their turn!.
        /// </summary>
        public static string PlayerPass {
            get {
                return ResourceManager.GetString("PlayerPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tiles you want to swap...Then press the FINISH button..
        /// </summary>
        public static string PlayerSwap {
            get {
                return ResourceManager.GetString("PlayerSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 3.
        /// </summary>
        public static string PlayerThree {
            get {
                return ResourceManager.GetString("PlayerThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}&apos;s turn..
        /// </summary>
        public static string PlayerTurn {
            get {
                return ResourceManager.GetString("PlayerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has finished their turn!.
        /// </summary>
        public static string PlayerTurnFinish {
            get {
                return ResourceManager.GetString("PlayerTurnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2.
        /// </summary>
        public static string PlayerTwo {
            get {
                return ResourceManager.GetString("PlayerTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} made the word: .
        /// </summary>
        public static string PlayerWord {
            get {
                return ResourceManager.GetString("PlayerWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} points).
        /// </summary>
        public static string RoundScore {
            get {
                return ResourceManager.GetString("RoundScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRABBLE.
        /// </summary>
        public static string ScrabbleName {
            get {
                return ResourceManager.GetString("ScrabbleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this window to start a new game!.
        /// </summary>
        public static string StartAgain {
            get {
                return ResourceManager.GetString("StartAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game... Start!.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAP.
        /// </summary>
        public static string SwapButton {
            get {
                return ResourceManager.GetString("SwapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} is first!.
        /// </summary>
        public static string TextFirstPlayer {
            get {
                return ResourceManager.GetString("TextFirstPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input by typing: .
        /// </summary>
        public static string TextInput {
            get {
                return ResourceManager.GetString("TextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAP then enter tile letter (IE: V D A)..., MOVE A(7,7)... to place tiles, PASS to pass, or RANK to rank..
        /// </summary>
        public static string TextInstructions {
            get {
                return ResourceManager.GetString("TextInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextInterface {
            get {
                return ResourceManager.GetString("TextInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Judge: You&apos;ve input a wrong command. Please try again.
        /// </summary>
        public static string TextJudgeCommand {
            get {
                return ResourceManager.GetString("TextJudgeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Judge: Wrong MOVE arguments. Please try again..
        /// </summary>
        public static string TextJudgeMove {
            get {
                return ResourceManager.GetString("TextJudgeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Judge: You didn&apos;t score. Please try again!.
        /// </summary>
        public static string TextNoScore {
            get {
                return ResourceManager.GetString("TextNoScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Judge: You can&apos;t swap from now on!.
        /// </summary>
        public static string TextNoSwap {
            get {
                return ResourceManager.GetString("TextNoSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0} player game..
        /// </summary>
        public static string TextNumofPlayer {
            get {
                return ResourceManager.GetString("TextNumofPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} - {1} | .
        /// </summary>
        public static string TextOnePlayerScore {
            get {
                return ResourceManager.GetString("TextOnePlayerScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has passed!.
        /// </summary>
        public static string TextPass {
            get {
                return ResourceManager.GetString("TextPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has finished their turn!.
        /// </summary>
        public static string TextPlayerFinish {
            get {
                return ResourceManager.GetString("TextPlayerFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Scores: .
        /// </summary>
        public static string TextPlayerScores {
            get {
                return ResourceManager.GetString("TextPlayerScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} made the word: .
        /// </summary>
        public static string TextPlayerWord {
            get {
                return ResourceManager.GetString("TextPlayerWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Submit or press ENTER key when you&apos;re done..
        /// </summary>
        public static string TextPressThis {
            get {
                return ResourceManager.GetString("TextPressThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} gets {1}!.
        /// </summary>
        public static string TextScore {
            get {
                return ResourceManager.GetString("TextScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game... Start!.
        /// </summary>
        public static string TextStartGame {
            get {
                return ResourceManager.GetString("TextStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has swapped their tiles!.
        /// </summary>
        public static string TextSwap {
            get {
                return ResourceManager.GetString("TextSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a score of {0}, Player {1} is the winner!.
        /// </summary>
        public static string TextWinner {
            get {
                return ResourceManager.GetString("TextWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} points).
        /// </summary>
        public static string TextWordScore {
            get {
                return ResourceManager.GetString("TextWordScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Tiles: .
        /// </summary>
        public static string TextYourTiles {
            get {
                return ResourceManager.GetString("TextYourTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your turn now!.
        /// </summary>
        public static string TextYourTurn {
            get {
                return ResourceManager.GetString("TextYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} gets {1}!.
        /// </summary>
        public static string TileChar {
            get {
                return ResourceManager.GetString("TileChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} - Desktop Scrabble.
        /// </summary>
        public static string ViewDesktopPlayer {
            get {
                return ResourceManager.GetString("ViewDesktopPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} - Text Scrabble.
        /// </summary>
        public static string ViewTextPlayer {
            get {
                return ResourceManager.GetString("ViewTextPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome players! Welcome to Scrabble!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string XAMLAbout {
            get {
                return ResourceManager.GetString("XAMLAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string XAMLHelp {
            get {
                return ResourceManager.GetString("XAMLHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your interfaces!.
        /// </summary>
        public static string XAMLInterface {
            get {
                return ResourceManager.GetString("XAMLInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        public static string XAMLPASS {
            get {
                return ResourceManager.GetString("XAMLPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURN TO RACK.
        /// </summary>
        public static string XAMLRACK {
            get {
                return ResourceManager.GetString("XAMLRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string XAMLStart {
            get {
                return ResourceManager.GetString("XAMLStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAP.
        /// </summary>
        public static string XAMLSWAP {
            get {
                return ResourceManager.GetString("XAMLSWAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrabble.
        /// </summary>
        public static string XAMLTitle {
            get {
                return ResourceManager.GetString("XAMLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Players!.
        /// </summary>
        public static string XAMLWelcome {
            get {
                return ResourceManager.GetString("XAMLWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your rack..
        /// </summary>
        public static string XAMLYourRack {
            get {
                return ResourceManager.GetString("XAMLYourRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your turn!.
        /// </summary>
        public static string YourTurn {
            get {
                return ResourceManager.GetString("YourTurn", resourceCulture);
            }
        }
    }
}
